Repository Torben-Tom/Portal, pull requests merged in 2023-06, with the labels that each got.

#22 Merge branch bugfix/release-latest into main
  .github/workflows/main.yml
  .github/workflows/staging.yml
Labels: bug

#24 Merge branch bugfix/build-scripts into main
  compile.ps1
  compile.sh
  dev.ps1
  dev.sh
Labels: bug

#32 Merge branch feature/math-fix into main
  src/ts/engine/entitiy/boundingbox.ts
  src/ts/engine/entitiy/entity.ts
  src/ts/engine/entitiy/entitymanager.ts
  src/ts/engine/input/inputhandler.ts
  src/ts/engine/math/point.ts
  src/ts/engine/math/rectangle.ts
  src/ts/engine/math/rectangulararea.ts
  src/ts/engine/math/vector2d.ts
  src/ts/game/entities/networkentity.ts
Labels: enhancement

#34 Merge branch feature/math-matrix2d into main
  src/ts/engine/math/matrix2d.ts
Labels: enhancement

#39 Merge branch feature/level1-new into main
  src/assets/bottomBrick.png
  src/assets/bridge.png
  src/assets/buttomBrick.png
  src/assets/button-ground.png
  src/assets/button-standing.png
  src/assets/characterArmLeft.png
  src/assets/characterArmRight.png
  src/assets/characterLeft.png
  src/assets/characterRight.png
  src/assets/companionCube.png
  src/assets/emptyBrick.png
  src/assets/goal.png
  src/assets/greenPortal.png
  src/assets/leftBrick.png
  src/assets/leftCornerBrick.png
  src/assets/middleBrick.png
  src/assets/playerJump.png
  src/assets/playerRunLeft.png
  src/assets/playerRunRight.png
  src/assets/purplePortal.png
  src/assets/rightBrick.png
  src/assets/rightCornerBrick.png
  src/html/index.html
  src/ts/engine/entitiy/boundingbox.ts
  src/ts/engine/entitiy/complexentity.ts
  src/ts/engine/entitiy/complexentitybuilder.ts
  src/ts/engine/entitiy/entity.ts
  src/ts/engine/entitiy/entitymanager.ts
  src/ts/engine/entitiy/touch.ts
  src/ts/engine/game.ts
  src/ts/engine/level/level.ts
  src/ts/engine/level/levelmanager.ts
  src/ts/engine/renderer/renderers/debugrenderer.ts
  src/ts/engine/renderer/renderers/entityrenderer.ts
  src/ts/game/entities/bottombrickentity.ts
  src/ts/game/entities/bridgeentity.ts
  src/ts/game/entities/buttonground.ts
  src/ts/game/entities/buttonstanding.ts
  src/ts/game/entities/companioncube.ts
  src/ts/game/entities/goal.ts
  src/ts/game/entities/leftbrickentity.ts
  src/ts/game/entities/leftcornerbrickentity.ts
  src/ts/game/entities/middlebrickentity.ts
  src/ts/game/entities/playerarmright.ts
  src/ts/game/entities/playerentity.ts
  src/ts/game/entities/portalentity.ts
  src/ts/game/entities/portalgreen.ts
  src/ts/game/entities/portalpurple.ts
  src/ts/game/entities/portaltype.ts
  src/ts/game/entities/rightbrickentity.ts
  src/ts/game/entities/rightcornerbrickentity.ts
  src/ts/game/gamesetup.ts
  src/ts/game/levels/level1.ts
Labels: enhancement

#40 merge Feature/level into main
  dev.sh
  src/html/index.html
  src/html/main.css
  src/ts/game/entities/goal.ts
  src/ts/game/entities/metalwallentity.ts
  src/ts/game/gamesetup.ts
  src/ts/game/levels/level1.ts
  src/ts/game/levels/level2.ts
  src/ts/game/levels/level3.ts
Labels: enhancement

#46 InputHandler right click
  src/ts/engine/entitiy/boundingbox.ts
  src/ts/engine/entitiy/entitymanager.ts
  src/ts/engine/entitiy/movingentity.ts
  src/ts/engine/event/events/mouseclickevent/mouseclickevent.ts
  src/ts/engine/event/events/mouseclickevent/mouseclickeventdata.ts
  src/ts/engine/input/inputhandler.ts
  src/ts/engine/input/mousebutton.ts
  src/ts/engine/math/diagonal.ts
  src/ts/engine/math/direction.ts
  src/ts/game/entities/playerentity.ts
  src/ts/game/entities/portalentity.ts
  src/ts/game/entities/portaltype.ts
  src/ts/game/levels/level1.ts
Labels: bug

#48 Merge branch feature/shoot-portals into main
  src/ts/engine/entitiy/boundingbox.ts
  src/ts/engine/entitiy/entity.ts
  src/ts/engine/entitiy/entitymanager.ts
  src/ts/engine/event/engineventhandler.ts
  src/ts/engine/input/inputhandler.ts
  src/ts/engine/math/matrix2d.ts
  src/ts/engine/math/vector2d.ts
  src/ts/game/entities/playerentity.ts
  src/ts/game/entities/portalentity.ts
  src/ts/game/levels/level1.ts
Labels: enhancement

#50 Merge branch feature/ci-cd into main
  .github/workflows/main.yml
  compile.sh
  dev.sh
  dockerfile
  tsconfig.json
Labels: enhancement

#51 Merge branch bugfix/ci-cd-pipeline-names into main
  .github/workflows/main.yml
Labels: bug

#53 Update README.md
  README.md
Labels: documentation

#55 merge someAdjustments into main
  src/assets/playerJump.png
  src/assets/playerRunLeft.png
  src/assets/playerRunRight.png
  src/html/index.html
  src/html/main.css
  src/ts/engine/entitiy/entity.ts
  src/ts/game/entities/networkentity.ts
  src/ts/game/entities/networkentity2.ts
  src/ts/game/entities/playerarm.ts
  src/ts/game/entities/playerarmright.ts
  src/ts/game/entities/playerentity.ts
  src/ts/game/entities/portalentity.ts
  src/ts/game/entities/portalgreen.ts
  src/ts/game/entities/portalpurple.ts
  src/ts/game/gamesetup.ts
  src/ts/game/levels/level1.ts
  src/ts/game/levels/level2.ts
  src/ts/game/levels/level3.ts
Labels: enhancement

#62 Merge branch feature/tps-tolerance into main
  src/ts/engine/game.ts
Labels: enhancement

#70 Adaptation for staging pipeline
  .github/workflows/staging.yml
Labels: bug, enhancement

#71 Edit Website Title and added Favicon
  README.md
  src/html/favicon.ico
  src/html/index.html
Labels: enhancement

#75 BugFixing
  src/ts/engine/event/events/keyboardevent/keyboardevent.ts
  src/ts/engine/event/events/keyboardevent/keyboardeventdata.ts
  src/ts/engine/input/inputhandler.ts
  src/ts/game/entities/buttonstanding.ts
  src/ts/game/gamesetup.ts
Labels: bug

#76 Merge branch feature/scenes into main
  src/ts/engine/enginesetup.ts
  src/ts/engine/entitiy/boundingbox.ts
  src/ts/engine/entitiy/icomplexentity.ts
  src/ts/engine/event/events/mouseclickevent/mouseclickevent.ts
  src/ts/engine/game.ts
  src/ts/engine/level/level.ts
  src/ts/engine/level/levelmanager.ts
  src/ts/engine/math/rectangle.ts
  src/ts/engine/renderer/compositor.ts
  src/ts/engine/renderer/renderers/debugrenderer.ts
  src/ts/engine/renderer/renderers/elementrenderer.ts
  src/ts/engine/renderer/renderers/scenerenderer.ts
  src/ts/engine/scene/element.ts
  src/ts/engine/scene/elements/button.ts
  src/ts/engine/scene/elements/checkbox.ts
  src/ts/engine/scene/elements/label.ts
  src/ts/engine/scene/elements/text.ts
  src/ts/engine/scene/scene.ts
  src/ts/engine/scene/scenemanager.ts
  src/ts/game/gamesetup.ts
  src/ts/game/levels/level1.ts
  src/ts/game/levels/level2.ts
  src/ts/game/main.ts
  src/ts/game/scenes/ingame.ts
  src/ts/game/scenes/mainmenu.ts
Labels: enhancement

#82 Added explain labels in level 1 and 2
  src/ts/game/gamesetup.ts
  src/ts/game/levels/level1.ts
  src/ts/game/levels/level2.ts
  src/ts/game/levels/level3.ts
  src/ts/game/scenes/level1scene.ts
  src/ts/game/scenes/level2scene.ts
  src/ts/game/scenes/leveloverview.ts
  src/ts/game/scenes/mainmenu.ts
Labels: enhancement

#83 Bug Fixed
  README.md
  src/ts/game/entities/playerentity.ts
  src/ts/game/levels/level1.ts
  src/ts/game/levels/level2.ts
Labels: bug

#84 reworked level 3
  src/ts/game/levels/level3.ts
Labels: bug

#85 Merge branch feature/settings into main
  src/ts/engine/entitiy/icomplexentity.ts
  src/ts/engine/game.ts
  src/ts/engine/level/levelmanager.ts
  src/ts/engine/renderer/renderers/debugrenderer.ts
  src/ts/engine/renderer/renderers/entityrenderer.ts
  src/ts/engine/scene/scenemanager.ts
  src/ts/engine/settings/setting.ts
  src/ts/engine/settings/settingsmanager.ts
  src/ts/engine/settings/simplesetting.ts
  src/ts/game/gamesetup.ts
  src/ts/game/levels/level1.ts
  src/ts/game/levels/level2.ts
  src/ts/game/levels/level3.ts
  src/ts/game/main.ts
  src/ts/game/scenes/gameover.ts
  src/ts/game/scenes/ingame.ts
  src/ts/game/scenes/leveloverview.ts
  src/ts/game/scenes/mainmenu.ts
Labels: enhancement

#90 Merge branch level4Simplify into main
  src/ts/game/levels/level4.ts
Labels: bug, enhancement

#93 Merge branch feature/audio-player into main
  src/ts/engine/audio/audioplayer.ts
  src/ts/engine/audio/audiotype.ts
  src/ts/engine/game.ts
  src/ts/engine/settings/setting.ts
  src/ts/engine/settings/settingsmanager.ts
Labels: enhancement

#96 Merge branch feature/level-cookies into main
  src/ts/engine/scene/element.ts
  src/ts/engine/scene/elements/button.ts
  src/ts/engine/scene/elements/checkbox.ts
  src/ts/engine/scene/elements/label.ts
  src/ts/engine/settings/simplesetting.ts
  src/ts/engine/time/dateutils.ts
  src/ts/game/levels/level1.ts
  src/ts/game/levels/level2.ts
  src/ts/game/levels/level3.ts
  src/ts/game/levels/level4.ts
  src/ts/game/scenes/leveloverview.ts
Labels: enhancement

#98 made adjustments on the readme file
  README.md
Labels: documentation, enhancement

#99 made PitchSlide for Portal
  Portal_PresentaionSlide.pptx
Labels: documentation

#101 Merge branch documentation/readme-update
  README.md
Labels: documentation

#102 Merge branch bugfix/infinite-asset-loading-loop into main
  src/ts/engine/assets/assetloader.ts
  src/ts/engine/game.ts
  src/ts/game/main.ts
  src/ts/game/scenes/leveloverview.ts
  src/ts/game/scenes/mainmenu.ts
Labels: bug, enhancement

#103 Merge branch bugfix/asset-loading-race-condition into main
  src/ts/engine/assets/assetloader.ts
  src/ts/engine/game.ts
  src/ts/game/main.ts
Labels: bug

#105 Merge branch bugfix/4-side-collision-response into main
  src/ts/engine/entitiy/entitymanager.ts
  src/ts/engine/entitiy/movingentity.ts
Labels: bug

#106 Merge branch documentation/presentation-update into main
  Portal Presentation Slide.pptx
  Portal_PresentaionSlide.pptx
Labels: documentation
